#!/bin/bash
cd "${0%/*}" || exit 1    # run from this directory
set -e  # exit when any command fails

eval "$(conda shell.bash hook)"
conda activate pumapy

mkdir -p $HOME/lib
cp $PuMA_DIR/python/TexGen/install/lib/libTexGenCore.dylib $HOME/lib

make clean && rm -rf source/files
sphinx-apidoc -o source/files ../python/pumapy
make html

rm $HOME/lib/libTexGenCore.dylib
